version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs-app
    restart: always
    expose:
      - 3000
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs:/var/log/nginx
    depends_on:
      - nextjs